name: Maven CI/CD

on:
 workflow_dispatch:

jobs:
  build_and_test:

    runs-on: ubuntu-latest
   
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        env: ./.env
    - name: run
      run: |
           echo my name is  ${{ secret.PORT }}
        
#     - name: Build project with Maven
#       run: |
#         cd Heritage
#         mvn clean install
      
    

      
